- name: remove directory
  tags:
  - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # backend --> /app, frontend --> user/share/nginx/html
    state: absent

- name: create directory
  tags:
  - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # backend --> /app, frontend --> user/share/nginx/html
    state: directory

- name: download the code
  tags:
  - deployment
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ APP_LOCATION }}" # backend --> /app, frontend --> user/share/nginx/html
    remote_src: yes